Feature/order
wecode-bootcamp-korea/35-1st-magazine-K-backend pull request #10
Opened 2022-07-26 06:48 UTC by ehdrb92

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 장바구니에 물품을 추가, 수정, 제거

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 유저가 장바구니에 보유하고 있는 상품 데이터 전송
- `GET`으로 장바구니 데이터 요청
- 요청 Header에 jwt를 함께 전송하여 유저 정보를 받는다.

![Screenshot from 2022-07-26 14-53-30](https://user-images.githubusercontent.com/98671555/180933389-93435043-473a-4103-b7dd-161b5fd2758b.png)
- 장바구니에 가진 데이터가 없을 경우 에러 반환

![Screenshot from 2022-07-26 14-46-59](https://user-images.githubusercontent.com/98671555/180933595-18062250-fd18-4038-947e-f2d4a15782b5.png)
![Screenshot from 2022-07-26 14-56-04](https://user-images.githubusercontent.com/98671555/180933711-d2544e6e-235b-4125-821d-0b98349f0c10.png)

2. 유저가 상품을 장바구니에 넣은 후 데이터 전송
- `POST`로 장바구니에 데이터를 넣은 후 결과 값 전송
- 요청 Header에 jwt를 함께 전송하여 유저 정보를 받는다.

![Screenshot from 2022-07-26 15-20-48](https://user-images.githubusercontent.com/98671555/180937327-45bd59dd-fca9-4d11-8ad3-9d6aa043e448.png)
- 요청 Body에 상품과 추가할 개수를 함께 전달한다.

![Screenshot from 2022-07-26 15-21-32](https://user-images.githubusercontent.com/98671555/180937453-625469c2-4a69-403b-9257-02202b2882b6.png)
- 요청에 대한 결과 값

![Screenshot from 2022-07-26 15-27-08](https://user-images.githubusercontent.com/98671555/180938418-fa9b8e3a-9864-41c1-90db-9bdec03e3870.png)
- 데이터베이스 테이블에 추가된 모습

![Screenshot from 2022-07-26 15-28-34](https://user-images.githubusercontent.com/98671555/180938562-1d526102-a161-4feb-b636-1ef6e322875e.png)
- 또 다른 상품을 장바구니에 추가 하였을 때, 결과

![Screenshot from 2022-07-26 15-30-16](https://user-images.githubusercontent.com/98671555/180939026-be060434-f358-491c-93d2-9282e346dfb0.png)
![Screenshot from 2022-07-26 15-32-09](https://user-images.githubusercontent.com/98671555/180939108-5b02c921-4b71-4fab-b78d-e144733a3127.png)

- 장바구니에 이미 존재하는 상품을 추가 하였을 때, 결과

![Screenshot from 2022-07-26 15-33-06](https://user-images.githubusercontent.com/98671555/180939318-aeb2562b-3a01-4cc0-a05e-a19510cca8cd.png)
![Screenshot from 2022-07-26 15-34-04](https://user-images.githubusercontent.com/98671555/180939382-b6e8cd45-1235-40a2-905b-778e2c4d8d29.png)

3. 장바구니에 담겨있는 상품의 수량을 조절하여 데이터 저장
- `PATCH`로 상품의 수량 조절 요청
- 요청 Header에 jwt를 함께 전송하여 유저 정보를 받는다.

![Screenshot from 2022-07-26 15-36-25](https://user-images.githubusercontent.com/98671555/180939774-926dc471-4f9e-4175-97c8-fe3b4b0c3fe6.png)

- 요청 Body에 수정하고 싶은 상품의 id와 더할 것인지 뺄것인지를 함께 전달했을 때, 결과

![Screenshot from 2022-07-26 15-38-27](https://user-images.githubusercontent.com/98671555/180940134-84bb09d4-3475-481e-ad41-0edebadc35bb.png)
![Screenshot from 2022-07-26 15-39-38](https://user-images.githubusercontent.com/98671555/180940288-476e6901-fa03-4aa6-b4e9-673f1032fbca.png)

4. 장바구니에 있는 상품을 삭제하고 결과 데이터 전송
- `DELETE`로 삭제 요청
- 요청 Header에 jwt를 함께 전송하여 유저 정보를 받는다.

![Screenshot from 2022-07-26 15-43-07](https://user-images.githubusercontent.com/98671555/180940851-cf52062e-bb42-4a88-b86f-42950e501144.png)

- 요청 Body에 삭제할 상품의 id를 전달했을 때, 결과

![Screenshot from 2022-07-26 15-42-34](https://user-images.githubusercontent.com/98671555/180940930-8ee5cf47-32dc-4633-a6cc-43336ba34787.png)
- 데이터 베이스에서 해당 상품이 삭제된 결과

![Screenshot from 2022-07-26 15-44-46](https://user-images.githubusercontent.com/98671555/180941143-000d8f1a-5cb1-4011-8d6c-c61da03815a2.png)

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 테이블끼리 복잡하게 참조하는 구조에서 필요한 데이터를 가져오는 방법에 대해 많이 생각해 볼 수 있었다.
- Q객체 사용에 대해 알 수 있게 되었다.

<br />

## :: 기타 질문 및 특이 사항
- 특정 데이터가 다른 데이터로부터 참조를 받고 있지않으면 자동으로 삭제되게 하는 로직이 구현되지 않았다. 해당 방법에 대해 좀 더 고민을 해보아야 할 것 같다.

2022-07-26 07:24 UTC, ehdrb92 commented
트렌젝션에 대한 내용이 아직 잘 이해되지 않아 일단 조건문을 추가하여 `DELETE` 요청에 장바구니 상태의 물건이 없을 경우 해당 오더가 함께 삭제되도록 해보았습니다.

해당 코드도 함께 리뷰 부탁드립니다.

2022-07-26 08:29 UTC, kyeongraekim requested changes

2022-07-26 08:29 UTC, kyeongraekim commented on magazinek/settings.py
> +    'django_extensions',
어떤 목적으로 사용하는 라이브러리? 혹은 모듈이실까요?

2022-07-26 08:29 UTC, kyeongraekim commented on magazinek/settings.py
> +    'django_extensions',
혹시 사용하지 않으시다면 삭제해주세요~

2022-07-26 08:29 UTC, kyeongraekim commented on orders/views.py
> +            CART_STATUS = 1
CART STATUS 와 같은 다양한 숫자값의 모음은 Enum Class를 선언하여서 관리해주세요~

2022-07-26 08:29 UTC, kyeongraekim commented on orders/views.py
> +            CART_STATUS = 1
관련하여 파이썬 공식 문서를 남겨드립니다~ https://docs.python.org/ko/3/library/enum.html

2022-07-26 08:29 UTC, kyeongraekim commented on orders/views.py
> +            cart_products = Order.objects.get(Q(user=User.objects.get(id=user.id)) & Q(order_status=CART_STATUS)).orderitem_set.all()
데코레이터를 통해서 받아온 16번 라인의 user는 이미 객체로서 존재하고 있습니다. Q객체 내부의 user 부분을 한 번 다시 고민해보세요~

2022-07-26 08:29 UTC, kyeongraekim commented on orders/views.py
> +            CART_STATUS = 1
Enum class 위 언급 부분 확인해주세요!~

2022-07-26 08:29 UTC, kyeongraekim commented on orders/views.py
> +            selected_product = Product.objects.get(id=product)
해당 내용은 path parameter로 접근할 수 있을 것 같네요~

2022-07-26 08:29 UTC, kyeongraekim commented on orders/views.py
> +                )
해당 부분은 내일 라이브코드 리뷰 시간에 함께 보시죠!

2022-07-26 08:33 UTC, ehdrb92 commented on magazinek/settings.py
> +    'django_extensions',
네 수정하도록 하겠습니다.

2022-07-26 09:40 UTC, ehdrb92 commented on orders/views.py
> +            cart_products = Order.objects.get(Q(user=User.objects.get(id=user.id)) & Q(order_status=CART_STATUS)).orderitem_set.all()
해당되는 부분들 모두 수정하였습니다.

2022-07-26 11:09 UTC, ehdrb92 commented on orders/views.py
> +                )
넵 알겠습니다.

2022-07-26 11:22 UTC, ehdrb92 commented on orders/views.py
> +            selected_product = Product.objects.get(id=product)
count 변수는 path parameter로 받도록 수정하였습니다.

2022-07-26 11:30 UTC, ehdrb92 commented on orders/views.py
> +            CART_STATUS = 1
Enum 클래스를 별도로 생성하여 코드 수정하였습니다.

2022-07-26 11:30 UTC, ehdrb92 commented on orders/views.py
> +            CART_STATUS = 1
넵 확인하였습니다.

2022-07-27 05:56 UTC, kyeongraekim requested changes
라이브 코드 리뷰 내용 기반으로 수정올려주시면 재확인하겠습니다!~

2022-07-27 05:56 UTC, kyeongraekim commented on orders/urls.py
> +    path('/cart/<int:count>', CartView.as_view())
count 내용은 바디에 담아서 전달해주세요~

2022-07-27 08:17 UTC, ehdrb92 commented on orders/urls.py
> +    path('/cart/<int:count>', CartView.as_view())
넵. 해당 사항 수정하였습니다.

2022-07-27 09:28 UTC, kyeongraekim requested changes

2022-07-27 09:28 UTC, kyeongraekim commented on magazinek/settings.py
> +    'django_extensions',
불필요한 라이브러리가 또 보이는 것 같네요!~

2022-07-27 09:28 UTC, kyeongraekim commented on orders/views.py
> +                Order.objects.get(user=user, order_status=OrderStatusEnum.CART.value).delete()
해당부분은 로직상 112번 이후에 무조건 발동 될 코드이네요. 제가 라이브 코드 리뷰 때 의도드렸던 사항은, 

```python
if not Order.objects.get(필터링 조건).orderitem_set.exists():
```

으로 시작하는 로직이었습니다. 푸시해주신 내용과 현재 내용의 차이를 한 번 살펴보세요!~

2022-07-27 09:33 UTC, kyeongraekim requested changes

2022-07-27 09:33 UTC, kyeongraekim commented on orders/views.py
> +                user_cart.update(order_status=OrderStatusEnum.DELIVERY_COMPLETED.value)
이곳이 order_status로 시작되면 또 attribute Error 가 나지 않나요? 한번 확인해주세요~

2022-07-27 10:23 UTC, ehdrb92 commented on magazinek/settings.py
> +    'django_extensions',
계속 실수하네요.... 수정하였습니다.

2022-07-27 11:27 UTC, ehdrb92 commented on orders/views.py
> +                user_cart.update(order_status=OrderStatusEnum.DELIVERY_COMPLETED.value)
생각해보니 `ForeignKey`라서 위와 같은 코드라면 객체가 들어가야 에러가 발생하지 않을 것 같은데 이상하게도 코드가 정상적으로 동작 하였습니다.

제가 `order_status`와 `order_status_id` 둘 다 테스트 해보았는데 둘 다 정상적으로 작동합니다.

일단 정상적인 코드는 `order_status_id`가 맞는 것 같아 코드는 수정하였습니다.

위의 코드가 정상적으로 작동하는 이유가 무엇인지는 한번 알아보도록 하겠습니다.

2022-07-27 12:06 UTC, ehdrb92 commented on orders/views.py
> +                Order.objects.get(user=user, order_status=OrderStatusEnum.CART.value).delete()
리뷰 반영하여 수정해보았습니다.

2022-07-28 01:58 UTC, kyeongraekim requested changes

2022-07-28 01:58 UTC, kyeongraekim commented on magazinek/settings.py
> +    'django_extensions'
해당 부분 삭제 잊지말아주세요~ 깃헙 메인에 푸시할 상용화될 코드는 꼭 git diff 찍어보시면서 주도면밀하게 관찰하고 올려주세요~

2022-07-28 01:58 UTC, kyeongraekim commented on orders/views.py
> +                cart_products.update(order_quantity=cart_products.first().order_quantity - 1)
현재는 재고 수량 관리를 안하고 있기 때문에 +에 대한 무한 증식은 문제 없어 보이지만, quantity는 모델링 구조상 수량이 음수로 되어서는 안될 텐데 이에 대한 예외처리도 한 번 추가하여 보세요~

2022-07-28 01:58 UTC, kyeongraekim commented on orders/views.py
> +            return JsonResponse({'result' : 'Modified'}, status = 200)
modified라는 영어 원어의 의미가 다소 불분명합니다. success 정도의 의미 전달이 더 올바를 것 같네요!

2022-07-28 01:58 UTC, kyeongraekim commented on orders/views.py
> +            if not Order.objects.get(user=user, order_status=OrderStatusEnum.CART.value).orderitem_set.exists():
get().exists() 와 filter().exists()의 차이를 고민해보시고 에러 핸들링을 어떻게 구사해야될지 고민해보세요~

2022-07-28 02:49 UTC, ehdrb92 commented on magazinek/settings.py
> +    'django_extensions'
넵.... 꼭 확인하는 습관 가지도록 하겠습니다.

2022-07-28 03:40 UTC, ehdrb92 commented on orders/views.py
> +            return JsonResponse({'result' : 'Modified'}, status = 200)
수정 하였습니다.

2022-07-28 04:39 UTC, ehdrb92 commented on orders/views.py
> +                cart_products.update(order_quantity=cart_products.first().order_quantity - 1)
해당 부분에 상품의 개수가 1개일 경우 수량을 줄일 수 없게 코드를 수정하였습니다.

2022-07-28 05:39 UTC, ehdrb92 commented on orders/views.py
> +            if not Order.objects.get(user=user, order_status=OrderStatusEnum.CART.value).orderitem_set.exists():
수정 완료 되었습니다.

2022-07-28 05:53 UTC, kyeongraekim approved these changes
LGTM!~

2022-07-28 05:53 UTC, merged