[35기 황유정] reviews post 기능 구현
wecode-bootcamp-korea/35-1st-magazine-K-backend pull request #18
Opened 2022-07-27 08:50 UTC by xoxowo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [x] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품 상세페이지 하단에 코멘트를 작성할 수 있는 기능 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 회원인 유저가 제품 상세페이지 하단에 제품에 대한 코멘트를 작성할 수 있는 create 기능 구현
2. confilct 해결 및 정확한 변수명 및 오탈자 수정

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 제품을 구매하지 않은 회원의 상태를 검증하는 부분에 오류발생으로 .. 코드 수정이 오래걸렸습니다..
- 오전 코드 리뷰 내용에 있던 내용 활용해봤습니다.

<br />

## :: 기타 질문 및 특이 사항
- enum 클래스 활용하니 32번줄이 길어졌는데... 음.. 필터 내부에 작성했던 조건을 다른줄로 바꿔야할지 궁금합니다.

2022-07-27 09:13 UTC, kyeongraekim requested changes

2022-07-27 09:13 UTC, kyeongraekim commented on reviews/views.py
> +            delivered       = OrderStatus.objects.get(id=5)
id 부분이 하드 코딩 되어있네요! 상용화된 코드에서 하드코딩은 지양해주세요~ 필요하다면 Enum Class를 이곳에서도 활용해주세요

2022-07-27 09:13 UTC, kyeongraekim commented on reviews/views.py
> +                user_id    = user.id,
user=user 로 객체적 접근이 가능하다는 점 다시 한 번 강조해드립니다~

2022-07-27 10:54 UTC, xoxowo commented on reviews/views.py
> +                user_id    = user.id,
넵! 오전 코드 보내주신거 확인하여 재수정했습니다.

2022-07-27 10:54 UTC, xoxowo commented on reviews/views.py
> +            delivered       = OrderStatus.objects.get(id=5)
넵 enum 클래스 활용했습니다.

2022-07-28 01:40 UTC, kyeongraekim requested changes
마이너한 수정 사항 확인해주세요~

2022-07-28 01:40 UTC, kyeongraekim commented on reviews/views.py
> +            orderd_products = OrderItem.objects.filter(order__user=user, order__order_status=OrderStatusEnum.DELIVERY_COMPLETED.value, product_id=product_id)
영문 원어로 변수명 작성시 오타 주의해주세요~

2022-07-28 02:21 UTC, xoxowo commented on reviews/views.py
> +            orderd_products = OrderItem.objects.filter(order__user=user, order__order_status=OrderStatusEnum.DELIVERY_COMPLETED.value, product_id=product_id)
넵 오타 수정했습니다 😱

2022-07-28 05:41 UTC, kyeongraekim approved these changes
LGTM!~

2022-07-28 05:41 UTC, merged