[35기 김동규] Magazine K 데이터베이스 모델링
wecode-bootcamp-korea/35-1st-magazine-K-backend pull request #2
Opened 2022-07-19 08:54 UTC by ehdrb92

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
Magazine K 데이터베이스 모델링

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. users app database modeling
- `TimeStempModel` : 생성 및 수정 시점을 기록하기 위한 목적 (상속을 목적)
- `User` : 회원 정보 데이터
-
2. products app database modeling
- `MainCategory` : 메인 카테고리 데이터
- `SubCategory` : 서브 카테고리 데이터
- `Product` : 상품 정보 데이터
- `ProductImage` : 상품 썸네일 이미지 데이터

3. orders app database modeling
- `OrderStatus` : 상품 주문 상태 데이터
- `Order` : 기타 주문 정보 데이터
- `OrderItem` : 주문 물품 정보 데이터

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
커머스 웹 사이트 모델링에 대한 전체적인 청사진을 어떤 식으로 그려야 할지에 대해 알 수 있는 시간을 가지게 되었다.

<br />

## :: 기타 질문 및 특이 사항
없음

2022-07-19 09:36 UTC, kyeongraekim requested changes
아래 내용 확인하신 후 수정해주세요!~

2022-07-19 09:36 UTC, kyeongraekim commented on orders/models.py
> +    order_number    = models.PositiveIntegerField()
난수화된 주문 번호가 들어갈 기획이라면 uuid field를 사용해주세요~ 
추후에 로직을 작성하실 때에는 uuid4 기능을 이용하여 난수를 넣는 기획으로 가면 좋을 것 같습니다!~

2022-07-19 09:36 UTC, kyeongraekim commented on orders/models.py
> +    order_price    = models.DecimalField(max_digits=10, decimal_places=2)
뒤에 붙는 max_digits와 decimal_places의 의미를 한 번 코멘트로 설명으로 남겨주세요!

2022-07-19 09:36 UTC, kyeongraekim commented on products/models.py
> +    sub_url    = models.TextField()
url은 textfield로 선언하기에는 그 데이터양이 적음으로 varchar 혹은 urlfield를 이용해주세요~

2022-07-19 09:36 UTC, kyeongraekim commented on orders/models.py
> +    user_id         = models.ForeignKey(User, on_delete=models.CASCADE)
user가 사라질 때 해당 주문 이력도 함께 사라지면 기업에서 과거 기록 관리를 하기가 힘들 것 같아보이네요! 
on_delete=models.CASCADE 말고 달리 고를 수 있는 옵션들이 무엇이 있을까 다음의 링크를 확인하신 후 한 번 고민해주세요!~ 
https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.ForeignKey.on_delete

2022-07-19 09:36 UTC, kyeongraekim commented on users/models.py
> +class TimeStempModel(models.Model):
- Stemp에 영문 오타가 났네요!
- TimeStampModel은 core라는 앱에 별도로 관리해주세요! 해당 내용은 user 모델 말고도 다른 수 많은 이력관리를 필요로하는 모델 클래스들이 사용되도록 현재 추상화가 되어 있기 때문에, 해당 클래스의 디렉토리상 위치도 users가 아닌 공통 기능을 담는 앱에서 관리를 해주셔야 하는 것 입니다~

2022-07-19 10:33 UTC, ehdrb92 commented on orders/models.py
> +    order_number    = models.PositiveIntegerField()
넵 코드 수정하였고, 추후 기능 구현시 참고하도록 하겠습니다.

2022-07-19 10:40 UTC, ehdrb92 commented on orders/models.py
> +    order_price    = models.DecimalField(max_digits=10, decimal_places=2)
`max_digits` : 숫자에 허용되는 최대 자릿 수, **소수점 자릿 수를 포함**한다. 그리고 decimal_places보다 크거나 같은 수만 가능하다.
`decimal_places` : 소수 자릿 수.

2022-07-19 10:40 UTC, ehdrb92 commented on products/models.py
> +    sub_url    = models.TextField()
수정하였습니다.

2022-07-19 11:57 UTC, ehdrb92 commented on orders/models.py
> +    user_id         = models.ForeignKey(User, on_delete=models.CASCADE)
회원이 탈퇴를 하여도 user 정보와 구매이력을 함께 살릴 수 있는 방법으로는 아래와 같이 생각해 보았습니다.

1. `on_delete=models.PROTECT`로 변경하여 참조를 받는 데이터를 삭제하지 못하게 변경
2. 기존의 참조를 받는 users 테이블에 회원 상태를 확인할 수 있는 column 추가(boolean type)
3. 회원 로그인 시 user 테이블의 회원 상태를 함께 검사하여 로그인이 되도록 로직 구성
4. 탈퇴한 회원정보와 구매정보는 법적인 보존기간이 지날 경우 자동으로 삭제되도록 설정

위의 방식이 적절한지 알 수없어 해당 방식을 아직 코드로 적용시켜 보지는 않았습니다.
지금은 `SET_NULL`을 적용시켜 구매이력만 남도록 수정해 보았습니다.

2022-07-19 11:59 UTC, ehdrb92 commented on users/models.py
> +class TimeStempModel(models.Model):
`core` 생성하여 상속할 클래스는 해당 app에 저장하도록 수정하였습니다.

2022-07-20 01:25 UTC, kyeongraekim requested changes

2022-07-20 01:25 UTC, kyeongraekim commented on orders/models.py
> +    order_status_id = models.ForeignKey(OrderStatus, on_delete=models.CASCADE)
파이썬 장고 특성상 foreignKey로 붙는 변수명뒤에 자동으로 _id가 붙는다는 것은 혹시 알고 계셨을까요? 
지금 mysql 테이블에 들어가서 user_id부분의 칼럼명이 어떻게 설정되어있는지 확인해주세요~ 그리고 문제가있다면 해당 내용을 일괄 수정해주세요~

2022-07-20 01:25 UTC, kyeongraekim commented on orders/models.py
> +    order_price    = models.DecimalField(max_digits=10, decimal_places=2)
잘 이해해주셨네요!~ 확인하였습니다~

2022-07-20 02:05 UTC, ehdrb92 commented on orders/models.py
> +    order_status_id = models.ForeignKey(OrderStatus, on_delete=models.CASCADE)
![Screenshot from 2022-07-20 11-04-07](https://user-images.githubusercontent.com/98671555/179880108-e001a51e-ee9d-47f3-8d7d-e8785ef0c227.png)
 '_id' 값이 자동으로 붙는걸 깜빡한 것 같습니다. 일괄 수정하였습니다.

2022-07-20 04:07 UTC, ehdrb92 commented
`sub_categories`와 `products` 테이블이 `1 : #` 관계인 것을 `# : #`로 수정하였습니다.

2022-07-20 04:54 UTC, kyeongraekim approved these changes
LGTM!~

2022-07-20 04:54 UTC, merged