[35기 김동규] 상품 메인 리스트 페이지 로직
wecode-bootcamp-korea/35-1st-magazine-K-backend pull request #5
Opened 2022-07-21 11:28 UTC by ehdrb92

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
상품 메인 리스트 페이지 데이터 전송 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. 상품 메인 리스트 데이터 처리
- category와 page정보를 url 엔드 포인트로 받아 페이지 구현
- limit offset 페이징 처리를 이용하여 페이지 구분 구현

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- Query parameter와 페이징 처리에 대해 알 수 있는 시간을 가졌다.

<br />

## :: 기타 질문 및 특이 사항
- product 데이터를 프론트에 전송할 때 product의 특정 칼럼에 대해 정렬을 하여 데이터를 전송하고 싶었지만 어려움이 생겨 막힘.

2022-07-22 00:37 UTC, kyeongraekim requested changes

2022-07-22 00:37 UTC, kyeongraekim commented on magazinek/urls.py
> +    path('products', include('products.urls'))
user 부분은이미 머지가 되어있기 때문에 로그인 회원가입 부분의 url이 함께 어우러져있어야 합니다. 그렇지 않으면 현재 이 내용이 머지되면 깃헙상에서 삭제가 되게 됩니다. 현재 제거해주신 부분 다시 수정고민해주세요~

2022-07-22 00:37 UTC, kyeongraekim commented on products/urls.py
> +from products.views import *
코드 내에서는 *의 사용을 적절히 필요한 순간에만 사용해주셔야 합니다. 정확한 모듈명을 가져와서 import문에 써주세요~

2022-07-22 00:37 UTC, kyeongraekim commented on products/views.py
> +from products.models import *
이곳도 위 부분 수정 고민해주세요~

2022-07-22 00:37 UTC, kyeongraekim commented on products/views.py
> +class MainView(View):
페이지 관점이 아닌 데이터 관점에서의 View로 네이밍을 선정해주세요~ ProductView 정도가 괜찮을 것 같네요~

2022-07-22 00:37 UTC, kyeongraekim commented on products/views.py
> +        page_size = 5
PAGE_SIZE 등으로 상수 데이터의 네이밍 컨벤션을 따라주세요~

2022-07-22 00:37 UTC, kyeongraekim commented on products/views.py
> +        offset    = int(limit - page_size)
offset limit 값은 클라이언트에서 그냥 받아올 수는 없을까요? 이곳에서 page_size를 기준으로 연산이 필요하게 된 로직적 기획을 코멘트로 남겨주세요~

2022-07-22 00:37 UTC, kyeongraekim commented on products/views.py
> +
가독성과 애플리케이션 속도 면에서 더 뛰어난 list comprehension을 도입하여서 전체 리스트를 긁어오는 내용을 리팩토링 해보세요~

2022-07-22 03:07 UTC, ehdrb92 commented on magazinek/urls.py
> +    path('products', include('products.urls'))
`path('member', include('users.urls')),` 유저 부분 url을 함께 포함시켜 주었습니다.

2022-07-22 03:10 UTC, ehdrb92 commented on products/urls.py
> +from products.views import *
해당 부분 수정하였습니다.

2022-07-22 03:10 UTC, ehdrb92 commented on products/views.py
> +from products.models import *
해당 부분 수정하였습니다.

2022-07-22 04:02 UTC, ehdrb92 commented on products/views.py
> +class MainView(View):
네이밍 수정하였습니다.

2022-07-22 04:05 UTC, ehdrb92 commented on products/views.py
> +        page_size = 5
수정하였습니다.

2022-07-22 04:25 UTC, ehdrb92 commented on products/views.py
> +        offset    = int(limit - page_size)
사이트 제품 리스트를 페이지 당 5개씩 출력하도록 기획하였습니다.

구현을 위해 `PAGE_SIZE`의 값을 `5`라는 상수로 설정하였고, 슬라이싱을 하기 위해 `limit`, `offset`의 변수 연산을 위와 같이 만들었습니다.

만약에 클라이언트가 페이지 당 보고 싶은 개수를 설정하고 싶다면 `PAGE_SIZE`를 변수로 잡고, 쿼리 파라미터의 매개변수로 받게 하면 될 것 같습니다.

offset, limit 값을 각각 클라이언트로 받아오는 방법은 페이지 당 보고 싶은 개수를 설정할 수 있는 것 외에 사용하는 다른 이유가 또 있을까요?

2022-07-22 08:50 UTC, ehdrb92 commented on products/views.py
> +
리스트 표현식을 이용하여 코드 수정하였습니다.

2022-07-25 01:47 UTC, kyeongraekim requested changes

2022-07-25 01:47 UTC, kyeongraekim commented on products/views.py
> +            sorted_products = products.order_by('price')
해당 내용은 조건이 추가될 수록 불필요한 if-elfi 의 조건분기가 무한히 증가한다는 단점이 있습니다. 장고 ORM의 Q객체의 기능을 활용하여 접근해보세요~

2022-07-25 01:47 UTC, kyeongraekim commented on products/views.py
> +            sorted_products = products.order_by('price')
그리고 상용화된 코드에서는 0, 1, 2, 3 등의 팀 내부선에서만 공유될 수 있는 코드화된 용어의 사용을 지양해주세요~ 프론트 측과 소통하여 RESTful 하게 엔드포인트를 설정하여도 보안 등의 사항에 문제가 전혀 없음으로 영문으로 (sort_by = cheapest/newest/oldest 등) 표기를 이어가 주시면 더 좋을 것 같습니다~

2022-07-25 02:41 UTC, kyeongraekim requested changes

2022-07-25 02:41 UTC, kyeongraekim commented on magazinek/settings.py
> +    'django_extensions',
이 부분은 실제 코드상의 어떤 내용을 위해 첨가해주신 걸 까요?

2022-07-25 02:41 UTC, kyeongraekim commented on products/urls.py
> +    path('/list', ProductView.as_view())
/products/list 말고 /products 에서 끝내도 의미론적으로 기능적으로 무방한 URL가 될 것 같네요~

2022-07-25 02:41 UTC, kyeongraekim commented on products/views.py
> +            for product in sorted_products[offset:limit]]
offset limit의 형태가 [offset : offset+limit] 이 되어야 올바른 데이터 개수가 끊어서 전송될 수 있겠네요!~

2022-07-25 02:41 UTC, kyeongraekim commented on products/views.py
> +                'main_category' : product.category.get(id=category).name,
category가 직접 연결되어있는 product에서 출발되어서 뽑혀나오는 데이터라면 get() 메소드 사용이 굳이 필요 하지 않을 수 있겠네요~ 한 번 고민해보세요!

2022-07-25 03:38 UTC, ehdrb92 commented on magazinek/settings.py
> +    'django_extensions',
python shell_plus를 쓰기위해 추가한 앱입니다.

2022-07-25 03:38 UTC, ehdrb92 commented on products/urls.py
> +    path('/list', ProductView.as_view())
넵 수정하도록 하겠습니다.

2022-07-25 03:41 UTC, ehdrb92 commented on products/views.py
> +            for product in sorted_products[offset:limit]]
수정 완료되었습니다.

2022-07-25 12:17 UTC, ehdrb92 commented on products/views.py
> +            sorted_products = products.order_by('price')
현재 프로젝트에서 특정 값에 대응하는 필터(사이즈, 색상 등)가 기획에 없고, 특정 기준으로 정렬을 하는 기능만 존재합니다.
그래서 Q객체를 이용하여 데이터를 정렬하는 기능은 없다고 생각하여 별도로 Q객체를 적용시키지 않았습니다.

대신 알아본 바 조건문으로 분기를 하지않고 `order_by`에 들어갈 조건문을 클라이언트로 부터 받아 하는 방법으로 코드를 작성해 보았습니다. 적용을 시켰더니 조건문을 적용시켰을 때보다 깔끔해진 것을 볼 수 있었습니다.

그리고 해당 조건문들은 애초에 프론트측에서 전달하기 때문에 개발시 소통이 잘 되었다면, 조건문이 잘못들어오는 문제는 않생길 것이라 생각이 들었습니다.

2022-07-25 12:18 UTC, ehdrb92 commented on products/views.py
> +                'main_category' : product.category.get(id=category).name,
수정 완료되었습니다.

2022-07-25 12:36 UTC, ehdrb92 commented
브랜치를 삭제했다가 새로 생성하여 작업을 진행하였더니 `git pull`로 원격 main 브랜치의 커밋내용을 다 불러왔는데도 브랜치가 push 되지않아 `--force`로 강제 push를 하였습니다.

2022-07-26 01:18 UTC, kyeongraekim approved these changes

2022-07-26 01:18 UTC, merged