[35기 황유정] 제품 디테일 페이지 view 구현
wecode-bootcamp-korea/35-1st-magazine-K-backend pull request #7
Opened 2022-07-22 07:30 UTC by xoxowo

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 제품 디테일 페이지 view 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 쿼리파라미터의 키값으로 제품 카테고리 id와 제품 이슈id를 지정하여 벨류 값으로 제품 상세페이지 내용을 전달하는 productdetail class 를 정의 했습니다. 

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 쿼리 파라미터를 이용하여 제품 디테일 페이지에서 제품 정보를 모두 전달하는 로직을 구현해봤는데, RESTful한 API를 구현해보기 위해 더 많이 공부해야할 것 같습니다..

<br />

## :: 기타 질문 및 특이 사항
- 없습니다.

2022-07-22 08:17 UTC, kyeongraekim requested changes

2022-07-22 08:17 UTC, kyeongraekim commented on products/urls.py
> +    path('/detail', ProductDetailView.as_view()),
이곳에서 부터는 details라는 리소스 타겟 엔드포인트 보다,  path parameter를 받아서 정확한 product의 id값을 인자로 받아오면 좋을 것 같네요!~

2022-07-22 08:17 UTC, kyeongraekim commented on products/views.py
> +            product      = Product.objects.get(issue_number=issue_number)
실제 매거진 - b 기획처럼 이슈넘버가 아닌 product_id를 받아서 필터를 진행해주세요~

2022-07-22 08:17 UTC, kyeongraekim commented on products/views.py
> +                    'category'         : category.name,
백엔드 로직 선에서 해당 product가 category와 동일 한지 검증하는 로직이 있으면 좋겠네요~ 
클라이언트측에서 product, category를 실제 데이터 의도상과는 다르게 보내줘도 Get 함수는 문제없이 돌아갈 기획처럼 보여집니다~

2022-07-22 08:17 UTC, kyeongraekim commented on products/views.py
> +        except Product.DoesNotExist:
Model.DoesNotExist 에러가 상품에서만 나게끔 위 코드가 작성되었는지 여부를 다시 한 번 확인 해주세요~

2022-07-22 13:01 UTC, xoxowo commented on products/urls.py
> +    path('/detail', ProductDetailView.as_view()),
네 확인 후 수정했습니다.

2022-07-24 08:09 UTC, xoxowo commented on products/views.py
> +            product      = Product.objects.get(issue_number=issue_number)
넵!

2022-07-24 13:58 UTC, xoxowo commented on products/views.py
> +                    'category'         : category.name,
넵

2022-07-25 02:09 UTC, kyeongraekim requested changes

2022-07-25 02:09 UTC, kyeongraekim commented on products/views.py
> +                    'category'         : category[0]['category__name'],
category를 추출하는 내용이 불필요한 과도한 연산이 들어가져 있네요! category 테이블과 products테이블이 연결되어 있다면 product에서 출발하여 해당 데이터를 끌어올 수 있습니다.
13번째 라인의 내용을 "product.category.name" 으로 변경해서 한 번 통신 시험을 해보세요~

2022-07-25 04:12 UTC, xoxowo commented on products/views.py
> +                    'category'         : category[0]['category__name'],
이전에 Main과 Sub카테고리를 하나로 만들어서 다:다 관계로 제품이 카테고리를 여러개를 가지고있게되서, 제품 상세페이지에 나와있는 magazine b를 보여주고싶어 데이터를 가져왔습니다...

2022-07-26 01:08 UTC, kyeongraekim approved these changes
LGTM!~

2022-07-26 01:08 UTC, merged